const os = require('os');
const fs = require('fs');
// console.log(os.cpus().length);

// fs.appendFileSync("./t1.txt", "hello1");

//blocking operation
// console.log("first");
// const res = fs.readFileSync("./t1.txt", "utf-8");
// console.log(res);
// console.log("last");

// first
// hellohello1hello1hello1hello1
// last

// console.log("first");
// non blocking operation
// fs.readFile("./t1.txt", 'utf-8', (err, res) => {
//     console.log(res);
// })
// console.log("last");

// first
// last
// hellohello1hello1hello1hello1

const http = require('http');
const url = require('url')
const PORT = 4040;

const myServer = http.createServer((req, res) => {


    if (req.url == '/favicon.ico') return res.end();
    const { pathname, query } = url.parse(req.url, true); //obj create using
    const log = `${Date.now()} request generated by ${req.url} and pathname ${pathname}\n `;
    fs.appendFile('./log.txt', log, (err, res) => {
        console.log(query.search); //search val destructing 
        console.log(log);
    })
    res.end("server is start !!!");
});

myServer.listen(PORT, () => {
    console.log(`http://localhost:${PORT}`);
})


